	.set noreorder

#include "pspimport.s"

// Build List
// sceHprm_driver_0000.o sceHprm_driver_0001.o sceHprm_driver_0002.o sceHprm_driver_0003.o sceHprm_driver_0004.o sceHprm_driver_0005.o sceHprm_driver_0006.o sceHprm_driver_0007.o sceHprm_driver_0008.o sceHprm_driver_0009.o sceHprm_driver_0010.o sceHprm_driver_0011.o sceHprm_driver_0012.o sceHprm_driver_0013.o sceHprm_driver_0014.o sceHprm_driver_0015.o sceHprm_driver_0016.o sceHprm_driver_0017.o sceHprm_driver_0018.o sceHprm_driver_0019.o sceHprm_driver_0020.o sceHprm_driver_0021.o 

#ifdef F_sceHprm_driver_0000
	IMPORT_START	"sceHprm_driver",0x00010011
#endif
#ifdef F_sceHprm_driver_0001
	IMPORT_FUNC	"sceHprm_driver",0x103DF40C,sceHprm_driver_103DF40C
#endif
#ifdef F_sceHprm_driver_0002
	IMPORT_FUNC	"sceHprm_driver",0x1528D408,sceHprm_driver_1528D408
#endif
#ifdef F_sceHprm_driver_0003
	IMPORT_FUNC	"sceHprm_driver",0x1910B327,sceHprmPeekCurrentKey
#endif
#ifdef F_sceHprm_driver_0004
	IMPORT_FUNC	"sceHprm_driver",0x1C5BC5A0,sceHprmInit
#endif
#ifdef F_sceHprm_driver_0005
	IMPORT_FUNC	"sceHprm_driver",0x2C71594A,sceHprm_driver_2C71594A
#endif
#ifdef F_sceHprm_driver_0006
	IMPORT_FUNC	"sceHprm_driver",0x2C7B8B05,sceHprmResume
#endif
#ifdef F_sceHprm_driver_0007
	IMPORT_FUNC	"sceHprm_driver",0x3578F3B8,sceHprm_driver_3578F3B8
#endif
#ifdef F_sceHprm_driver_0008
	IMPORT_FUNC	"sceHprm_driver",0x49CCBE66,sceHprm_driver_49CCBE66
#endif
#ifdef F_sceHprm_driver_0009
	IMPORT_FUNC	"sceHprm_driver",0x526BB7F4,sceHprmSuspend
#endif
#ifdef F_sceHprm_driver_0010
	IMPORT_FUNC	"sceHprm_driver",0x588845DA,sceHprmEnd
#endif
#ifdef F_sceHprm_driver_0011
	IMPORT_FUNC	"sceHprm_driver",0x6ACEEE48,sceHprm_driver_6ACEEE48
#endif
#ifdef F_sceHprm_driver_0012
	IMPORT_FUNC	"sceHprm_driver",0x7A529B00,sceHprm_driver_7A529B00
#endif
#ifdef F_sceHprm_driver_0013
	IMPORT_FUNC	"sceHprm_driver",0x7CC2B27E,sceHprm_driver_7CC2B27E
#endif
#ifdef F_sceHprm_driver_0014
	IMPORT_FUNC	"sceHprm_driver",0x96251271,sceHprm_driver_96251271
#endif
#ifdef F_sceHprm_driver_0015
	IMPORT_FUNC	"sceHprm_driver",0xBE93F58A,sceHprm_driver_BE93F58A
#endif
#ifdef F_sceHprm_driver_0016
	IMPORT_FUNC	"sceHprm_driver",0xBEB0E9B2,sceHprm_driver_BEB0E9B2
#endif
#ifdef F_sceHprm_driver_0017
	IMPORT_FUNC	"sceHprm_driver",0xC7EA8BAC,sceHprm_driver_C7EA8BAC
#endif
#ifdef F_sceHprm_driver_0018
	IMPORT_FUNC	"sceHprm_driver",0xCFF04390,sceHprm_driver_CFF04390
#endif
#ifdef F_sceHprm_driver_0019
	IMPORT_FUNC	"sceHprm_driver",0xE5501183,sceHprm_driver_E5501183
#endif
#ifdef F_sceHprm_driver_0020
	IMPORT_FUNC	"sceHprm_driver",0xEFBD46FA,sceHprm_driver_EFBD46FA
#endif
#ifdef F_sceHprm_driver_0021
	IMPORT_FUNC	"sceHprm_driver",0xF0AA1FB9,sceHprm_driver_F0AA1FB9
#endif
