	.set noreorder

#include "pspimport.s"

// Build List
// sceCtrl_driver_0000.o sceCtrl_driver_0001.o sceCtrl_driver_0002.o sceCtrl_driver_0003.o sceCtrl_driver_0004.o sceCtrl_driver_0005.o sceCtrl_driver_0006.o sceCtrl_driver_0007.o sceCtrl_driver_0008.o sceCtrl_driver_0009.o sceCtrl_driver_0010.o sceCtrl_driver_0011.o sceCtrl_driver_0012.o sceCtrl_driver_0013.o sceCtrl_driver_0014.o sceCtrl_driver_0015.o sceCtrl_driver_0016.o sceCtrl_driver_0017.o sceCtrl_driver_0018.o sceCtrl_driver_0019.o sceCtrl_driver_0020.o sceCtrl_driver_0021.o sceCtrl_driver_0022.o sceCtrl_driver_0023.o sceCtrl_driver_0024.o sceCtrl_driver_0025.o sceCtrl_driver_0026.o sceCtrl_driver_0027.o 

#ifdef F_sceCtrl_driver_0000
	IMPORT_START	"sceCtrl_driver",0x00010011
#endif
#ifdef F_sceCtrl_driver_0001
	IMPORT_FUNC	"sceCtrl_driver",0x0B7AC633,sceCtrl_driver_5C56C779
#endif
#ifdef F_sceCtrl_driver_0002
	IMPORT_FUNC	"sceCtrl_driver",0x28E71A16,sceCtrlSetSamplingMode
#endif
#ifdef F_sceCtrl_driver_0003
	IMPORT_FUNC	"sceCtrl_driver",0x312646B8,sceCtrl_driver_A88E8D22
#endif
#ifdef F_sceCtrl_driver_0004
	IMPORT_FUNC	"sceCtrl_driver",0x37B6B9E9,sceCtrl_driver_348D99D4
#endif
#ifdef F_sceCtrl_driver_0005
	IMPORT_FUNC	"sceCtrl_driver",0x454455AC,sceCtrlReadBufferPositive
#endif
#ifdef F_sceCtrl_driver_0006
	IMPORT_FUNC	"sceCtrl_driver",0x4DEA8065,sceCtrlResume
#endif
#ifdef F_sceCtrl_driver_0007
	IMPORT_FUNC	"sceCtrl_driver",0x5FCA31C5,sceCtrl_driver_B7CEAED4
#endif
#ifdef F_sceCtrl_driver_0008
	IMPORT_FUNC	"sceCtrl_driver",0x655DB613,sceCtrl_driver_252D3A8D
#endif
#ifdef F_sceCtrl_driver_0009
	IMPORT_FUNC	"sceCtrl_driver",0x6D74BF08,sceCtrlSetSamplingCycle
#endif
#ifdef F_sceCtrl_driver_0010
	IMPORT_FUNC	"sceCtrl_driver",0x6F3B46FB,sceCtrlSetIdleCancelThreshold
#endif
#ifdef F_sceCtrl_driver_0011
	IMPORT_FUNC	"sceCtrl_driver",0x7DF19E59,sceCtrlReadLatch
#endif
#ifdef F_sceCtrl_driver_0012
	IMPORT_FUNC	"sceCtrl_driver",0x8182D8A0,sceCtrlPeekBufferNegative
#endif
#ifdef F_sceCtrl_driver_0013
	IMPORT_FUNC	"sceCtrl_driver",0x84F8AD25,sceCtrlSuspend
#endif
#ifdef F_sceCtrl_driver_0014
	IMPORT_FUNC	"sceCtrl_driver",0x8FE1D531,sceCtrlGetSamplingCycle
#endif
#ifdef F_sceCtrl_driver_0015
	IMPORT_FUNC	"sceCtrl_driver",0xB1AE49F8,sceCtrlInit
#endif
#ifdef F_sceCtrl_driver_0016
	IMPORT_FUNC	"sceCtrl_driver",0xBB14FB66,sceCtrl_driver_CC70B61E
#endif
#ifdef F_sceCtrl_driver_0017
	IMPORT_FUNC	"sceCtrl_driver",0xBCE989DD,sceCtrl_AF5960F3
#endif
#ifdef F_sceCtrl_driver_0018
	IMPORT_FUNC	"sceCtrl_driver",0xC4AAD55F,sceCtrlPeekBufferPositive
#endif
#ifdef F_sceCtrl_driver_0019
	IMPORT_FUNC	"sceCtrl_driver",0xCE223F52,sceCtrlSetRapidFire
#endif
#ifdef F_sceCtrl_driver_0020
	IMPORT_FUNC	"sceCtrl_driver",0xD30D9B80,sceCtrlEnd
#endif
#ifdef F_sceCtrl_driver_0021
	IMPORT_FUNC	"sceCtrl_driver",0xD7F23B0B,sceCtrlGetSamplingMode
#endif
#ifdef F_sceCtrl_driver_0022
	IMPORT_FUNC	"sceCtrl_driver",0xDB3CD94C,sceCtrl_driver_5E77BC8A
#endif
#ifdef F_sceCtrl_driver_0023
	IMPORT_FUNC	"sceCtrl_driver",0xDB6F93CB,sceCtrl_driver_7CA723DC
#endif
#ifdef F_sceCtrl_driver_0024
	IMPORT_FUNC	"sceCtrl_driver",0xEA6EDF43,sceCtrlPeekLatch
#endif
#ifdef F_sceCtrl_driver_0025
	IMPORT_FUNC	"sceCtrl_driver",0xEF06B8B2,sceCtrlClearRapidFire
#endif
#ifdef F_sceCtrl_driver_0026
	IMPORT_FUNC	"sceCtrl_driver",0xF3630971,sceCtrlGetIdleCancelThreshold
#endif
#ifdef F_sceCtrl_driver_0027
	IMPORT_FUNC	"sceCtrl_driver",0xFF847C31,sceCtrlReadBufferNegative
#endif
