	.set noreorder

#include "pspimport.s"

// Build List
// sceDve_driver_0000.o sceDve_driver_0001.o sceDve_driver_0002.o sceDve_driver_0003.o sceDve_driver_0004.o sceDve_driver_0005.o sceDve_driver_0006.o sceDve_driver_0007.o sceDve_driver_0008.o sceDve_driver_0009.o sceDve_driver_0010.o sceDve_driver_0011.o sceDve_driver_0012.o sceDve_driver_0013.o sceDve_driver_0014.o sceDve_driver_0015.o sceDve_driver_0016.o sceDve_driver_0017.o sceDve_driver_0018.o sceDve_driver_0019.o sceDve_driver_0020.o sceDve_driver_0021.o sceDve_driver_0022.o 

#ifdef F_sceDve_driver_0000
	IMPORT_START	"sceDve_driver",0x00010011
#endif
#ifdef F_sceDve_driver_0001
	IMPORT_FUNC	"sceDve_driver",0x0836B2B5,sceDve_driver_0836B2B5
#endif
#ifdef F_sceDve_driver_0002
	IMPORT_FUNC	"sceDve_driver",0x0B85524C,sceDve_driver_0B85524C
#endif
#ifdef F_sceDve_driver_0003
	IMPORT_FUNC	"sceDve_driver",0x17BC42E4,sceDve_driver_17BC42E4
#endif
#ifdef F_sceDve_driver_0004
	IMPORT_FUNC	"sceDve_driver",0x22D50DA7,sceDve_driver_22D50DA7
#endif
#ifdef F_sceDve_driver_0005
	IMPORT_FUNC	"sceDve_driver",0x292F15DA,sceDve_driver_292F15DA
#endif
#ifdef F_sceDve_driver_0006
	IMPORT_FUNC	"sceDve_driver",0x34E9274D,sceDve_driver_34E9274D
#endif
#ifdef F_sceDve_driver_0007
	IMPORT_FUNC	"sceDve_driver",0x36970008,sceDve_driver_36970008
#endif
#ifdef F_sceDve_driver_0008
	IMPORT_FUNC	"sceDve_driver",0x59E1B113,sceDve_driver_59E1B113
#endif
#ifdef F_sceDve_driver_0009
	IMPORT_FUNC	"sceDve_driver",0x93828323,sceDve_driver_93828323
#endif
#ifdef F_sceDve_driver_0010
	IMPORT_FUNC	"sceDve_driver",0xA265B504,sceDve_driver_A265B504
#endif
#ifdef F_sceDve_driver_0011
	IMPORT_FUNC	"sceDve_driver",0xA2D53F99,sceDve_driver_A2D53F99
#endif
#ifdef F_sceDve_driver_0012
	IMPORT_FUNC	"sceDve_driver",0xADE8C471,sceDve_driver_ADE8C471
#endif
#ifdef F_sceDve_driver_0013
	IMPORT_FUNC	"sceDve_driver",0xAE2A6570,sceDve_driver_AE2A6570
#endif
#ifdef F_sceDve_driver_0014
	IMPORT_FUNC	"sceDve_driver",0xB2E4E437,sceDve_driver_B2E4E437
#endif
#ifdef F_sceDve_driver_0015
	IMPORT_FUNC	"sceDve_driver",0xB7827F16,sceDve_driver_B7827F16
#endif
#ifdef F_sceDve_driver_0016
	IMPORT_FUNC	"sceDve_driver",0xBF910381,sceDve_driver_BF910381
#endif
#ifdef F_sceDve_driver_0017
	IMPORT_FUNC	"sceDve_driver",0xC9362C91,sceDve_driver_C9362C91
#endif
#ifdef F_sceDve_driver_0018
	IMPORT_FUNC	"sceDve_driver",0xD8863512,sceDve_driver_D8863512
#endif
#ifdef F_sceDve_driver_0019
	IMPORT_FUNC	"sceDve_driver",0xD986F31B,sceDve_driver_D986F31B
#endif
#ifdef F_sceDve_driver_0020
	IMPORT_FUNC	"sceDve_driver",0xDEB2F80C,sceDve_driver_DEB2F80C
#endif
#ifdef F_sceDve_driver_0021
	IMPORT_FUNC	"sceDve_driver",0xE84E975E,sceDve_driver_E84E975E
#endif
#ifdef F_sceDve_driver_0022
	IMPORT_FUNC	"sceDve_driver",0xF0CF5A67,sceDve_driver_F0CF5A67
#endif
