	.set noreorder

#include "pspimport.s"

// Build List
// KDebugForKernel_0000.o KDebugForKernel_0001.o KDebugForKernel_0002.o KDebugForKernel_0003.o KDebugForKernel_0004.o KDebugForKernel_0005.o KDebugForKernel_0006.o KDebugForKernel_0007.o KDebugForKernel_0008.o KDebugForKernel_0009.o KDebugForKernel_0010.o KDebugForKernel_0011.o KDebugForKernel_0012.o KDebugForKernel_0013.o KDebugForKernel_0014.o KDebugForKernel_0015.o KDebugForKernel_0016.o KDebugForKernel_0017.o KDebugForKernel_0018.o KDebugForKernel_0019.o KDebugForKernel_0020.o KDebugForKernel_0021.o KDebugForKernel_0022.o KDebugForKernel_0023.o KDebugForKernel_0024.o KDebugForKernel_0025.o KDebugForKernel_0026.o KDebugForKernel_0027.o KDebugForKernel_0028.o KDebugForKernel_0029.o 

#ifdef F_KDebugForKernel_0000
	IMPORT_START	"KDebugForKernel",0x00010011
#endif
#ifdef F_KDebugForKernel_0001
	IMPORT_FUNC	"KDebugForKernel",0x23906FB2,KDebugForKernel_23906FB2
#endif
#ifdef F_KDebugForKernel_0002
	IMPORT_FUNC	"KDebugForKernel",0x24C32559,KDebugForKernel_24C32559
#endif
#ifdef F_KDebugForKernel_0003
	IMPORT_FUNC	"KDebugForKernel",0x2FF4E9F9,KDebugForKernel_2FF4E9F9
#endif
#ifdef F_KDebugForKernel_0004
	IMPORT_FUNC	"KDebugForKernel",0x333DCEC7,KDebugForKernel_333DCEC7
#endif
#ifdef F_KDebugForKernel_0005
	IMPORT_FUNC	"KDebugForKernel",0x428A8DA3,KDebugForKernel_428A8DA3
#endif
#ifdef F_KDebugForKernel_0006
	IMPORT_FUNC	"KDebugForKernel",0x5282DD5E,KDebugForKernel_5282DD5E
#endif
#ifdef F_KDebugForKernel_0007
	IMPORT_FUNC	"KDebugForKernel",0x5CE9838B,KDebugForKernel_5CE9838B
#endif
#ifdef F_KDebugForKernel_0008
	IMPORT_FUNC	"KDebugForKernel",0x66253C4E,KDebugForKernel_66253C4E
#endif
#ifdef F_KDebugForKernel_0009
	IMPORT_FUNC	"KDebugForKernel",0x72E6B3B8,KDebugForKernel_72E6B3B8
#endif
#ifdef F_KDebugForKernel_0010
	IMPORT_FUNC	"KDebugForKernel",0x7CEB2C09,KDebugForKernel_7CEB2C09
#endif
#ifdef F_KDebugForKernel_0011
	IMPORT_FUNC	"KDebugForKernel",0x7D1C74F0,KDebugForKernel_7D1C74F0
#endif
#ifdef F_KDebugForKernel_0012
	IMPORT_FUNC	"KDebugForKernel",0x84F370BC,KDebugForKernel_84F370BC
#endif
#ifdef F_KDebugForKernel_0013
	IMPORT_FUNC	"KDebugForKernel",0x8B041DFB,KDebugForKernel_8B041DFB
#endif
#ifdef F_KDebugForKernel_0014
	IMPORT_FUNC	"KDebugForKernel",0x9B868276,KDebugForKernel_9B868276
#endif
#ifdef F_KDebugForKernel_0015
	IMPORT_FUNC	"KDebugForKernel",0x9F8703E4,KDebugForKernel_9F8703E4
#endif
#ifdef F_KDebugForKernel_0016
	IMPORT_FUNC	"KDebugForKernel",0xA126F497,KDebugForKernel_A126F497
#endif
#ifdef F_KDebugForKernel_0017
	IMPORT_FUNC	"KDebugForKernel",0xA216AE06,KDebugForKernel_A216AE06
#endif
#ifdef F_KDebugForKernel_0018
	IMPORT_FUNC	"KDebugForKernel",0xA2983280,KDebugForKernel_A2983280
#endif
#ifdef F_KDebugForKernel_0019
	IMPORT_FUNC	"KDebugForKernel",0xAFB8FC80,KDebugForKernel_AFB8FC80
#endif
#ifdef F_KDebugForKernel_0020
	IMPORT_FUNC	"KDebugForKernel",0xB7251823,KDebugForKernel_B7251823
#endif
#ifdef F_KDebugForKernel_0021
	IMPORT_FUNC	"KDebugForKernel",0xB9C643C9,KDebugForKernel_B9C643C9
#endif
#ifdef F_KDebugForKernel_0022
	IMPORT_FUNC	"KDebugForKernel",0xD636B827,KDebugForKernel_D636B827
#endif
#ifdef F_KDebugForKernel_0023
	IMPORT_FUNC	"KDebugForKernel",0xDBB5597F,KDebugForKernel_DBB5597F
#endif
#ifdef F_KDebugForKernel_0024
	IMPORT_FUNC	"KDebugForKernel",0xE146606D,KDebugForKernel_E146606D
#endif
#ifdef F_KDebugForKernel_0025
	IMPORT_FUNC	"KDebugForKernel",0xE6554FDA,KDebugForKernel_E6554FDA
#endif
#ifdef F_KDebugForKernel_0026
	IMPORT_FUNC	"KDebugForKernel",0xE7A3874D,KDebugForKernel_E7A3874D
#endif
#ifdef F_KDebugForKernel_0027
	IMPORT_FUNC	"KDebugForKernel",0xE892D9A1,KDebugForKernel_E892D9A1
#endif
#ifdef F_KDebugForKernel_0028
	IMPORT_FUNC	"KDebugForKernel",0xEE75658D,KDebugForKernel_EE75658D
#endif
#ifdef F_KDebugForKernel_0029
	IMPORT_FUNC	"KDebugForKernel",0xFFD2F2B9,KDebugForKernel_FFD2F2B9
#endif
