	.set noreorder

#include "pspimport.s"

// Build List
// sceSuspendForKernel_0000.o sceSuspendForKernel_0001.o sceSuspendForKernel_0002.o sceSuspendForKernel_0003.o sceSuspendForKernel_0004.o sceSuspendForKernel_0005.o sceSuspendForKernel_0006.o sceSuspendForKernel_0007.o sceSuspendForKernel_0008.o sceSuspendForKernel_0009.o sceSuspendForKernel_0010.o sceSuspendForKernel_0011.o sceSuspendForKernel_0012.o sceSuspendForKernel_0013.o sceSuspendForKernel_0014.o sceSuspendForKernel_0015.o sceSuspendForKernel_0016.o 

#ifdef F_sceSuspendForKernel_0000
	IMPORT_START	"sceSuspendForKernel",0x00010011
#endif
#ifdef F_sceSuspendForKernel_0001
	IMPORT_FUNC	"sceSuspendForKernel",0x090CCB3F,sceSuspendForKernel_090CCB3F
#endif
#ifdef F_sceSuspendForKernel_0002
	IMPORT_FUNC	"sceSuspendForKernel",0x0AB0C6F3,sceSuspendForKernel_0AB0C6F3
#endif
#ifdef F_sceSuspendForKernel_0003
	IMPORT_FUNC	"sceSuspendForKernel",0x3AEE7261,sceSuspendForKernel_3AEE7261
#endif
#ifdef F_sceSuspendForKernel_0004
	IMPORT_FUNC	"sceSuspendForKernel",0x3E0271D3,sceSuspendForKernel_3E0271D3
#endif
#ifdef F_sceSuspendForKernel_0005
	IMPORT_FUNC	"sceSuspendForKernel",0x67B59042,sceSuspendForKernel_67B59042
#endif
#ifdef F_sceSuspendForKernel_0006
	IMPORT_FUNC	"sceSuspendForKernel",0x8F58B1EC,sceSuspendForKernel_8F58B1EC
#endif
#ifdef F_sceSuspendForKernel_0007
	IMPORT_FUNC	"sceSuspendForKernel",0x91A77137,sceSuspendForKernel_91A77137
#endif
#ifdef F_sceSuspendForKernel_0008
	IMPORT_FUNC	"sceSuspendForKernel",0x98A1D061,sceSuspendForKernel_98A1D061
#endif
#ifdef F_sceSuspendForKernel_0009
	IMPORT_FUNC	"sceSuspendForKernel",0xA14F40B2,sceSuspendForKernel_A14F40B2
#endif
#ifdef F_sceSuspendForKernel_0010
	IMPORT_FUNC	"sceSuspendForKernel",0xA569E425,sceSuspendForKernel_A569E425
#endif
#ifdef F_sceSuspendForKernel_0011
	IMPORT_FUNC	"sceSuspendForKernel",0xB2C9640B,sceSuspendForKernel_B2C9640B
#endif
#ifdef F_sceSuspendForKernel_0012
	IMPORT_FUNC	"sceSuspendForKernel",0xB43D1A8C,sceSuspendForKernel_B43D1A8C
#endif
#ifdef F_sceSuspendForKernel_0013
	IMPORT_FUNC	"sceSuspendForKernel",0xB53B2147,sceSuspendForKernel_B53B2147
#endif
#ifdef F_sceSuspendForKernel_0014
	IMPORT_FUNC	"sceSuspendForKernel",0xBDE686CD,sceSuspendForKernel_BDE686CD
#endif
#ifdef F_sceSuspendForKernel_0015
	IMPORT_FUNC	"sceSuspendForKernel",0xC7C928C7,sceSuspendForKernel_C7C928C7
#endif
#ifdef F_sceSuspendForKernel_0016
	IMPORT_FUNC	"sceSuspendForKernel",0xEADB1BD7,sceSuspendForKernel_EADB1BD7
#endif
