	.set noreorder

#include "pspimport.s"

// Build List
// SysMemUserForUser_0000.o SysMemUserForUser_0001.o SysMemUserForUser_0002.o SysMemUserForUser_0003.o SysMemUserForUser_0004.o SysMemUserForUser_0005.o SysMemUserForUser_0006.o SysMemUserForUser_0007.o SysMemUserForUser_0008.o SysMemUserForUser_0009.o SysMemUserForUser_0010.o SysMemUserForUser_0011.o SysMemUserForUser_0012.o SysMemUserForUser_0013.o SysMemUserForUser_0014.o SysMemUserForUser_0015.o SysMemUserForUser_0016.o SysMemUserForUser_0017.o SysMemUserForUser_0018.o SysMemUserForUser_0019.o 

#ifdef F_SysMemUserForUser_0000
	IMPORT_START	"SysMemUserForUser",0x40000011
#endif
#ifdef F_SysMemUserForUser_0001
	IMPORT_FUNC	"SysMemUserForUser",0x13A5ABEF,SysMemUserForUser_13A5ABEF
#endif
#ifdef F_SysMemUserForUser_0002
	IMPORT_FUNC	"SysMemUserForUser",0x237DBD4F,SysMemUserForUser_237DBD4F
#endif
#ifdef F_SysMemUserForUser_0003
	IMPORT_FUNC	"SysMemUserForUser",0x2A3E5280,SysMemUserForUser_2A3E5280
#endif
#ifdef F_SysMemUserForUser_0004
	IMPORT_FUNC	"SysMemUserForUser",0x342061E5,SysMemUserForUser_342061E5
#endif
#ifdef F_SysMemUserForUser_0005
	IMPORT_FUNC	"SysMemUserForUser",0x39F49610,SysMemUserForUser_39F49610
#endif
#ifdef F_SysMemUserForUser_0006
	IMPORT_FUNC	"SysMemUserForUser",0x3FC9AE6A,SysMemUserForUser_3FC9AE6A
#endif
#ifdef F_SysMemUserForUser_0007
	IMPORT_FUNC	"SysMemUserForUser",0x50F61D8A,SysMemUserForUser_50F61D8A
#endif
#ifdef F_SysMemUserForUser_0008
	IMPORT_FUNC	"SysMemUserForUser",0x6231A71D,SysMemUserForUser_6231A71D
#endif
#ifdef F_SysMemUserForUser_0009
	IMPORT_FUNC	"SysMemUserForUser",0x7591C7DB,SysMemUserForUser_7591C7DB
#endif
#ifdef F_SysMemUserForUser_0010
	IMPORT_FUNC	"SysMemUserForUser",0x9D9A5BA1,SysMemUserForUser_9D9A5BA1
#endif
#ifdef F_SysMemUserForUser_0011
	IMPORT_FUNC	"SysMemUserForUser",0xA291F107,SysMemUserForUser_A291F107
#endif
#ifdef F_SysMemUserForUser_0012
	IMPORT_FUNC	"SysMemUserForUser",0xA6848DF8,SysMemUserForUser_A6848DF8
#endif
#ifdef F_SysMemUserForUser_0013
	IMPORT_FUNC	"SysMemUserForUser",0xACBD88CA,SysMemUserForUser_ACBD88CA
#endif
#ifdef F_SysMemUserForUser_0014
	IMPORT_FUNC	"SysMemUserForUser",0xB6D61D02,SysMemUserForUser_B6D61D02
#endif
#ifdef F_SysMemUserForUser_0015
	IMPORT_FUNC	"SysMemUserForUser",0xDB83A952,SysMemUserForUser_DB83A952
#endif
#ifdef F_SysMemUserForUser_0016
	IMPORT_FUNC	"SysMemUserForUser",0xF77D77CB,SysMemUserForUser_F77D77CB
#endif
#ifdef F_SysMemUserForUser_0017
	IMPORT_FUNC	"SysMemUserForUser",0xF919F628,SysMemUserForUser_F919F628
#endif
#ifdef F_SysMemUserForUser_0018
	IMPORT_FUNC	"SysMemUserForUser",0xFC114573,SysMemUserForUser_FC114573
#endif
#ifdef F_SysMemUserForUser_0019
	IMPORT_FUNC	"SysMemUserForUser",0xFE707FDF,SysMemUserForUser_FE707FDF
#endif
