	.set noreorder

#include "pspimport.s"

// Build List
// sceMesgLed_driver_0000.o sceMesgLed_driver_0001.o sceMesgLed_driver_0002.o sceMesgLed_driver_0003.o sceMesgLed_driver_0004.o sceMesgLed_driver_0005.o sceMesgLed_driver_0006.o sceMesgLed_driver_0007.o sceMesgLed_driver_0008.o sceMesgLed_driver_0009.o sceMesgLed_driver_0010.o sceMesgLed_driver_0011.o sceMesgLed_driver_0012.o sceMesgLed_driver_0013.o sceMesgLed_driver_0014.o sceMesgLed_driver_0015.o sceMesgLed_driver_0016.o sceMesgLed_driver_0017.o sceMesgLed_driver_0018.o sceMesgLed_driver_0019.o sceMesgLed_driver_0020.o sceMesgLed_driver_0021.o sceMesgLed_driver_0022.o sceMesgLed_driver_0023.o 

#ifdef F_sceMesgLed_driver_0000
	IMPORT_START	"sceMesgLed_driver",0x00090011
#endif
#ifdef F_sceMesgLed_driver_0001
	IMPORT_FUNC	"sceMesgLed_driver",0x07037789,sceMesgLed_driver_07037789
#endif
#ifdef F_sceMesgLed_driver_0002
	IMPORT_FUNC	"sceMesgLed_driver",0x28238305,sceMesgLed_driver_28238305
#endif
#ifdef F_sceMesgLed_driver_0003
	IMPORT_FUNC	"sceMesgLed_driver",0x28BC34E1,sceMesgLed_driver_28BC34E1
#endif
#ifdef F_sceMesgLed_driver_0004
	IMPORT_FUNC	"sceMesgLed_driver",0x3702348B,sceMesgLed_driver_3702348B
#endif
#ifdef F_sceMesgLed_driver_0005
	IMPORT_FUNC	"sceMesgLed_driver",0x418BC5CF,sceMesgLed_driver_418BC5CF
#endif
#ifdef F_sceMesgLed_driver_0006
	IMPORT_FUNC	"sceMesgLed_driver",0x4A680E6B,sceMesgLed_driver_4A680E6B
#endif
#ifdef F_sceMesgLed_driver_0007
	IMPORT_FUNC	"sceMesgLed_driver",0x4E139EE3,sceMesgLed_driver_4E139EE3
#endif
#ifdef F_sceMesgLed_driver_0008
	IMPORT_FUNC	"sceMesgLed_driver",0x55E4F665,sceMesgLed_driver_55E4F665
#endif
#ifdef F_sceMesgLed_driver_0009
	IMPORT_FUNC	"sceMesgLed_driver",0x5FDB29F3,sceMesgLed_driver_5FDB29F3
#endif
#ifdef F_sceMesgLed_driver_0010
	IMPORT_FUNC	"sceMesgLed_driver",0x6039ED19,sceMesgLed_driver_6039ED19
#endif
#ifdef F_sceMesgLed_driver_0011
	IMPORT_FUNC	"sceMesgLed_driver",0x739D8E56,sceMesgLed_driver_739D8E56
#endif
#ifdef F_sceMesgLed_driver_0012
	IMPORT_FUNC	"sceMesgLed_driver",0x7EDF7F6E,sceMesgLed_driver_7EDF7F6E
#endif
#ifdef F_sceMesgLed_driver_0013
	IMPORT_FUNC	"sceMesgLed_driver",0x8B0310A0,sceMesgLed_driver_8B0310A0
#endif
#ifdef F_sceMesgLed_driver_0014
	IMPORT_FUNC	"sceMesgLed_driver",0x8F096FEC,sceMesgLed_driver_8F096FEC
#endif
#ifdef F_sceMesgLed_driver_0015
	IMPORT_FUNC	"sceMesgLed_driver",0xAA59DE09,sceMesgLed_driver_AA59DE09
#endif
#ifdef F_sceMesgLed_driver_0016
	IMPORT_FUNC	"sceMesgLed_driver",0xC15F737B,sceMesgLed_driver_C15F737B
#endif
#ifdef F_sceMesgLed_driver_0017
	IMPORT_FUNC	"sceMesgLed_driver",0xC40F29E2,sceMesgLed_driver_C40F29E2
#endif
#ifdef F_sceMesgLed_driver_0018
	IMPORT_FUNC	"sceMesgLed_driver",0xCE7E00DF,sceMesgLed_driver_CE7E00DF
#endif
#ifdef F_sceMesgLed_driver_0019
	IMPORT_FUNC	"sceMesgLed_driver",0xD4C47F58,sceMesgLed_driver_D4C47F58
#endif
#ifdef F_sceMesgLed_driver_0020
	IMPORT_FUNC	"sceMesgLed_driver",0xDA8B5C2E,sceMesgLed_driver_DA8B5C2E
#endif
#ifdef F_sceMesgLed_driver_0021
	IMPORT_FUNC	"sceMesgLed_driver",0xDFF0F308,sceMesgLed_driver_DFF0F308
#endif
#ifdef F_sceMesgLed_driver_0022
	IMPORT_FUNC	"sceMesgLed_driver",0xED47F024,sceMesgLed_driver_ED47F024
#endif
#ifdef F_sceMesgLed_driver_0023
	IMPORT_FUNC	"sceMesgLed_driver",0xF7275198,sceMesgLed_driver_F7275198
#endif
