	.set noreorder

#include "pspimport.s"


#ifdef F_sceSyscon_driver_0000
	IMPORT_START	"sceSyscon_driver",0x00010011
#endif
#ifdef F_sceSyscon_driver_0001
	IMPORT_FUNC	"sceSyscon_driver",0x00E7B6C2,sceSyscon_driver_00E7B6C2
#endif
#ifdef F_sceSyscon_driver_0002
	IMPORT_FUNC	"sceSyscon_driver",0x01677F91,sceSysconCtrlVoltage
#endif
#ifdef F_sceSyscon_driver_0003
	IMPORT_FUNC	"sceSyscon_driver",0x04EEFD03,sceSyscon_driver_04EEFD03
#endif
#ifdef F_sceSyscon_driver_0004
	IMPORT_FUNC	"sceSyscon_driver",0x051186F3,sceSyscon_driver_051186F3
#endif
#ifdef F_sceSyscon_driver_0005
	IMPORT_FUNC	"sceSyscon_driver",0x05727A0B,sceSyscon_driver_05727A0B
#endif
#ifdef F_sceSyscon_driver_0006
	IMPORT_FUNC	"sceSyscon_driver",0x07A0C260,sceSyscon_driver_07A0C260
#endif
#ifdef F_sceSyscon_driver_0007
	IMPORT_FUNC	"sceSyscon_driver",0x081826B4,sceSysconSuspend
#endif
#ifdef F_sceSyscon_driver_0008
	IMPORT_FUNC	"sceSyscon_driver",0x08234E6D,sceSysconReceiveSetParam
#endif
#ifdef F_sceSyscon_driver_0009
	IMPORT_FUNC	"sceSyscon_driver",0x08DA3752,sceSysconCtrlTachyonVoltage
#endif
#ifdef F_sceSyscon_driver_0010
	IMPORT_FUNC	"sceSyscon_driver",0x09721F7F,sceSysconGetPowerStatus
#endif
#ifdef F_sceSyscon_driver_0011
	IMPORT_FUNC	"sceSyscon_driver",0x0A771482,sceSysconInit
#endif
#ifdef F_sceSyscon_driver_0012
	IMPORT_FUNC	"sceSyscon_driver",0x1165C864,sceSyscon_driver_1165C864
#endif
#ifdef F_sceSyscon_driver_0013
	IMPORT_FUNC	"sceSyscon_driver",0x138747DE,sceSysconGetUmdSwitch
#endif
#ifdef F_sceSyscon_driver_0014
	IMPORT_FUNC	"sceSyscon_driver",0x1602ED0D,sceSysconCmdCancel
#endif
#ifdef F_sceSyscon_driver_0015
	IMPORT_FUNC	"sceSyscon_driver",0x18BFBE65,sceSysconCtrlLED
#endif
#ifdef F_sceSyscon_driver_0016
	IMPORT_FUNC	"sceSyscon_driver",0x19D5A97A,sceSyscon_driver_19D5A97A
#endif
#ifdef F_sceSyscon_driver_0017
	IMPORT_FUNC	"sceSyscon_driver",0x1A08CD66,sceSysconCtrlDvePower
#endif
#ifdef F_sceSyscon_driver_0018
	IMPORT_FUNC	"sceSyscon_driver",0x1B17D3E3,sceSyscon_driver_1B17D3E3
#endif
#ifdef F_sceSyscon_driver_0019
	IMPORT_FUNC	"sceSyscon_driver",0x204F23FF,sceSysconGetBaryonStatus2
#endif
#ifdef F_sceSyscon_driver_0020
	IMPORT_FUNC	"sceSyscon_driver",0x25F47F96,sceSyscon_driver_25F47F96
#endif
#ifdef F_sceSyscon_driver_0021
	IMPORT_FUNC	"sceSyscon_driver",0x284FE366,sceSysconBatteryGetLimitTime
#endif
#ifdef F_sceSyscon_driver_0022
	IMPORT_FUNC	"sceSyscon_driver",0x2B9E6A06,sceSysconGetPowerError
#endif
#ifdef F_sceSyscon_driver_0023
	IMPORT_FUNC	"sceSyscon_driver",0x2EE82492,sceSyscon_driver_2EE82492
#endif
#ifdef F_sceSyscon_driver_0024
	IMPORT_FUNC	"sceSyscon_driver",0x32CFD20F,sceSysconIsLowBattery
#endif
#ifdef F_sceSyscon_driver_0025
	IMPORT_FUNC	"sceSyscon_driver",0x3357EE5C,sceSyscon_driver_3357EE5C
#endif
#ifdef F_sceSyscon_driver_0026
	IMPORT_FUNC	"sceSyscon_driver",0x34C36FF9,sceSysconGetDigitalKey
#endif
#ifdef F_sceSyscon_driver_0027
	IMPORT_FUNC	"sceSyscon_driver",0x36E28C5F,sceSysconBatteryAuth
#endif
#ifdef F_sceSyscon_driver_0028
	IMPORT_FUNC	"sceSyscon_driver",0x373EC933,sceSysconBatteryGetElec
#endif
#ifdef F_sceSyscon_driver_0029
	IMPORT_FUNC	"sceSyscon_driver",0x3987FEA3,sceSysconCtrlUsbPower
#endif
#ifdef F_sceSyscon_driver_0030
	IMPORT_FUNC	"sceSyscon_driver",0x3AB3AEEF,sceSyscon_driver_3AB3AEEF
#endif
#ifdef F_sceSyscon_driver_0031
	IMPORT_FUNC	"sceSyscon_driver",0x3AC3D2A4,sceSysconCmdExecAsync
#endif
#ifdef F_sceSyscon_driver_0032
	IMPORT_FUNC	"sceSyscon_driver",0x3C6DB1C5,sceSyscon_driver_3C6DB1C5
#endif
#ifdef F_sceSyscon_driver_0033
	IMPORT_FUNC	"sceSyscon_driver",0x3C739F57,sceSysconGetHRPowerCtrl
#endif
#ifdef F_sceSyscon_driver_0034
	IMPORT_FUNC	"sceSyscon_driver",0x3DE38336,sceSysconReadPommelReg
#endif
#ifdef F_sceSyscon_driver_0035
	IMPORT_FUNC	"sceSyscon_driver",0x44439604,sceSysconCtrlHRPower
#endif
#ifdef F_sceSyscon_driver_0036
	IMPORT_FUNC	"sceSyscon_driver",0x48AB0E44,sceSysconGetLeptonPowerCtrl
#endif
#ifdef F_sceSyscon_driver_0037
	IMPORT_FUNC	"sceSyscon_driver",0x4C0EE2FA,sceSysconBatteryGetChargeTime
#endif
#ifdef F_sceSyscon_driver_0038
	IMPORT_FUNC	"sceSyscon_driver",0x4C539345,sceSysconBatteryGetTotalElec
#endif
#ifdef F_sceSyscon_driver_0039
	IMPORT_FUNC	"sceSyscon_driver",0x52B74B6C,sceSysconGetTachyonAwPowerCtrl
#endif
#ifdef F_sceSyscon_driver_0040
	IMPORT_FUNC	"sceSyscon_driver",0x53072985,sceSysconSetWlanSwitchCallback
#endif
#ifdef F_sceSyscon_driver_0041
	IMPORT_FUNC	"sceSyscon_driver",0x565EF519,sceSyscon_driver_565EF519
#endif
#ifdef F_sceSyscon_driver_0042
	IMPORT_FUNC	"sceSyscon_driver",0x56931095,sceSysconResume
#endif
#ifdef F_sceSyscon_driver_0043
	IMPORT_FUNC	"sceSyscon_driver",0x56A73EDD,sceSysconGetBtPowerStatus
#endif
#ifdef F_sceSyscon_driver_0044
	IMPORT_FUNC	"sceSyscon_driver",0x58531E69,sceSyscon_driver_58531E69
#endif
#ifdef F_sceSyscon_driver_0045
	IMPORT_FUNC	"sceSyscon_driver",0x59CD0449,sceSyscon_driver_59CD0449
#endif
#ifdef F_sceSyscon_driver_0046
	IMPORT_FUNC	"sceSyscon_driver",0x5B9ACC97,sceSysconCmdExec
#endif
#ifdef F_sceSyscon_driver_0047
	IMPORT_FUNC	"sceSyscon_driver",0x5EE92F3C,sceSysconSetDebugHandlers
#endif
#ifdef F_sceSyscon_driver_0048
	IMPORT_FUNC	"sceSyscon_driver",0x5F19C00F,sceSysconGetLcdPowerCtrl
#endif
#ifdef F_sceSyscon_driver_0049
	IMPORT_FUNC	"sceSyscon_driver",0x5FF1D610,sceSyscon_driver_5FF1D610
#endif
#ifdef F_sceSyscon_driver_0050
	IMPORT_FUNC	"sceSyscon_driver",0x628F2351,sceSysconGetMsPowerCtrl
#endif
#ifdef F_sceSyscon_driver_0051
	IMPORT_FUNC	"sceSyscon_driver",0x64FA0B22,sceSyscon_driver_64FA0B22
#endif
#ifdef F_sceSyscon_driver_0052
	IMPORT_FUNC	"sceSyscon_driver",0x65EB6096,sceSyscon_driver_65EB6096
#endif
#ifdef F_sceSyscon_driver_0053
	IMPORT_FUNC	"sceSyscon_driver",0x6848D817,sceSysconSetUmdSwitchCallback
#endif
#ifdef F_sceSyscon_driver_0054
	IMPORT_FUNC	"sceSyscon_driver",0x68EF0BEF,sceSyscon_driver_68EF0BEF
#endif
#ifdef F_sceSyscon_driver_0055
	IMPORT_FUNC	"sceSyscon_driver",0x6A53F3F8,sceSysconBatteryGetStatusCap
#endif
#ifdef F_sceSyscon_driver_0056
	IMPORT_FUNC	"sceSyscon_driver",0x6C911742,sceSysconWriteAlarm
#endif
#ifdef F_sceSyscon_driver_0057
	IMPORT_FUNC	"sceSyscon_driver",0x7016161C,sceSysconGetWlanPowerStatus
#endif
#ifdef F_sceSyscon_driver_0058
	IMPORT_FUNC	"sceSyscon_driver",0x70C10E61,sceSysconBatteryGetTemp
#endif
#ifdef F_sceSyscon_driver_0059
	IMPORT_FUNC	"sceSyscon_driver",0x71135D7D,sceSysconBatteryGetFullCap
#endif
#ifdef F_sceSyscon_driver_0060
	IMPORT_FUNC	"sceSyscon_driver",0x71AE1BCE,sceSysconGetHRPowerStatus
#endif
#ifdef F_sceSyscon_driver_0061
	IMPORT_FUNC	"sceSyscon_driver",0x72EDA9AF,sceSyscon_driver_72EDA9AF
#endif
#ifdef F_sceSyscon_driver_0062
	IMPORT_FUNC	"sceSyscon_driver",0x7479DB05,sceSysconSetHoldSwitchCallback
#endif
#ifdef F_sceSyscon_driver_0063
	IMPORT_FUNC	"sceSyscon_driver",0x75025299,sceSysconBatteryGetStatus
#endif
#ifdef F_sceSyscon_driver_0064
	IMPORT_FUNC	"sceSyscon_driver",0x75D22BF8,sceSysconBatteryGetElecAD
#endif
#ifdef F_sceSyscon_driver_0065
	IMPORT_FUNC	"sceSyscon_driver",0x7A805EE4,sceSysconReadAlarm
#endif
#ifdef F_sceSyscon_driver_0066
	IMPORT_FUNC	"sceSyscon_driver",0x7BCC5EAE,sceSyscon_driver_7BCC5EAE
#endif
#ifdef F_sceSyscon_driver_0067
	IMPORT_FUNC	"sceSyscon_driver",0x7C8A5503,sceSyscon_driver_7C8A5503
#endif
#ifdef F_sceSyscon_driver_0068
	IMPORT_FUNC	"sceSyscon_driver",0x7CBD4522,sceSysconBatteryGetIFC
#endif
#ifdef F_sceSyscon_driver_0069
	IMPORT_FUNC	"sceSyscon_driver",0x7EC5A957,sceSysconGetBaryonVersion
#endif
#ifdef F_sceSyscon_driver_0070
	IMPORT_FUNC	"sceSyscon_driver",0x805180D1,sceSysconSetHRPowerCallback
#endif
#ifdef F_sceSyscon_driver_0071
	IMPORT_FUNC	"sceSyscon_driver",0x806D4D6C,sceSyscon_driver_806D4D6C
#endif
#ifdef F_sceSyscon_driver_0072
	IMPORT_FUNC	"sceSyscon_driver",0x82861DE2,sceSysconBatteryGetRCap
#endif
#ifdef F_sceSyscon_driver_0073
	IMPORT_FUNC	"sceSyscon_driver",0x86D4CAD8,sceSysconGetBaryonStatus
#endif
#ifdef F_sceSyscon_driver_0074
	IMPORT_FUNC	"sceSyscon_driver",0x87671B18,sceSysconBatteryGetVoltAD
#endif
#ifdef F_sceSyscon_driver_0075
	IMPORT_FUNC	"sceSyscon_driver",0x876CA580,sceSysconBatteryGetCap
#endif
#ifdef F_sceSyscon_driver_0076
	IMPORT_FUNC	"sceSyscon_driver",0x882F0AAB,sceSyscon_driver_882F0AAB
#endif
#ifdef F_sceSyscon_driver_0077
	IMPORT_FUNC	"sceSyscon_driver",0x88FDB279,sceSysconSetBtSwitchCallback
#endif
#ifdef F_sceSyscon_driver_0078
	IMPORT_FUNC	"sceSyscon_driver",0x8A4519F5,sceSysconCtrlLeptonPower
#endif
#ifdef F_sceSyscon_driver_0079
	IMPORT_FUNC	"sceSyscon_driver",0x8BDEBB1E,sceSysconBatteryGetVolt
#endif
#ifdef F_sceSyscon_driver_0080
	IMPORT_FUNC	"sceSyscon_driver",0x8CBC7987,sceSysconResetDevice
#endif
#ifdef F_sceSyscon_driver_0081
	IMPORT_FUNC	"sceSyscon_driver",0x8DDA4CA6,sceSyscon_driver_8DDA4CA6
#endif
#ifdef F_sceSyscon_driver_0082
	IMPORT_FUNC	"sceSyscon_driver",0x8EDF1AD7,sceSysconGetBtPowerCtrl
#endif
#ifdef F_sceSyscon_driver_0083
	IMPORT_FUNC	"sceSyscon_driver",0x91E183CB,sceSysconPowerSuspend
#endif
#ifdef F_sceSyscon_driver_0084
	IMPORT_FUNC	"sceSyscon_driver",0x92D16FC7,sceSysconEnd
#endif
#ifdef F_sceSyscon_driver_0085
	IMPORT_FUNC	"sceSyscon_driver",0x9478F399,sceSysconCtrlLcdPower
#endif
#ifdef F_sceSyscon_driver_0086
	IMPORT_FUNC	"sceSyscon_driver",0x992C22C2,sceSysconSendSetParam
#endif
#ifdef F_sceSyscon_driver_0087
	IMPORT_FUNC	"sceSyscon_driver",0x99BBB24C,sceSysconCtrlMsPower
#endif
#ifdef F_sceSyscon_driver_0088
	IMPORT_FUNC	"sceSyscon_driver",0x9C4266FC,sceSysconCtrlBtPower
#endif
#ifdef F_sceSyscon_driver_0089
	IMPORT_FUNC	"sceSyscon_driver",0x9E6E060F,sceSyscon_driver_9E6E060F
#endif
#ifdef F_sceSyscon_driver_0090
	IMPORT_FUNC	"sceSyscon_driver",0xA068B3D0,sceSysconSetAlarmCallback
#endif
#ifdef F_sceSyscon_driver_0091
	IMPORT_FUNC	"sceSyscon_driver",0xA6776FB4,sceSysconGetBtSwitch
#endif
#ifdef F_sceSyscon_driver_0092
	IMPORT_FUNC	"sceSyscon_driver",0xA8E34316,sceSyscon_driver_A8E34316
#endif
#ifdef F_sceSyscon_driver_0093
	IMPORT_FUNC	"sceSyscon_driver",0xA975F224,sceSyscon_driver_A975F224
#endif
#ifdef F_sceSyscon_driver_0094
	IMPORT_FUNC	"sceSyscon_driver",0xA9AEF39F,sceSyscon_driver_A9AEF39F
#endif
#ifdef F_sceSyscon_driver_0095
	IMPORT_FUNC	"sceSyscon_driver",0xAD555CE5,sceSysconSetLowBatteryCallback
#endif
#ifdef F_sceSyscon_driver_0096
	IMPORT_FUNC	"sceSyscon_driver",0xB2558E37,sceSysconCtrlTachyonAwPower
#endif
#ifdef F_sceSyscon_driver_0097
	IMPORT_FUNC	"sceSyscon_driver",0xB5105D51,sceSysconBatteryGetCycle
#endif
#ifdef F_sceSyscon_driver_0098
	IMPORT_FUNC	"sceSyscon_driver",0xB71B98A8,sceSysconBatteryGetTempAD
#endif
#ifdef F_sceSyscon_driver_0099
	IMPORT_FUNC	"sceSyscon_driver",0xBAAECDF8,sceSysconSetBtPowerCallback
#endif
#ifdef F_sceSyscon_driver_0100
	IMPORT_FUNC	"sceSyscon_driver",0xBBFB70C0,sceSysconSetHPConnectCallback
#endif
#ifdef F_sceSyscon_driver_0101
	IMPORT_FUNC	"sceSyscon_driver",0xBDA16E46,sceSysconGetWlanSwitch
#endif
#ifdef F_sceSyscon_driver_0102
	IMPORT_FUNC	"sceSyscon_driver",0xBE27FE66,sceSysconCtrlPower
#endif
#ifdef F_sceSyscon_driver_0103
	IMPORT_FUNC	"sceSyscon_driver",0xC4D66C1D,sceSysconReadClock
#endif
#ifdef F_sceSyscon_driver_0104
	IMPORT_FUNC	"sceSyscon_driver",0xC5075828,sceSyscon_driver_C5075828
#endif
#ifdef F_sceSyscon_driver_0105
	IMPORT_FUNC	"sceSyscon_driver",0xC68F1573,sceSyscon_driver_C68F1573
#endif
#ifdef F_sceSyscon_driver_0106
	IMPORT_FUNC	"sceSyscon_driver",0xC7634A7A,sceSysconWriteClock
#endif
#ifdef F_sceSyscon_driver_0107
	IMPORT_FUNC	"sceSyscon_driver",0xC8439C57,sceSysconPowerStandby
#endif
#ifdef F_sceSyscon_driver_0108
	IMPORT_FUNC	"sceSyscon_driver",0xC8D97773,sceSyscon_driver_C8D97773
#endif
#ifdef F_sceSyscon_driver_0109
	IMPORT_FUNC	"sceSyscon_driver",0xCC04A978,sceSysconGetWlanLedCtrl
#endif
#ifdef F_sceSyscon_driver_0110
	IMPORT_FUNC	"sceSyscon_driver",0xCE76F93E,sceSysconGetDvePowerCtrl
#endif
#ifdef F_sceSyscon_driver_0111
	IMPORT_FUNC	"sceSyscon_driver",0xD1B501E8,sceSysconWritePommelReg
#endif
#ifdef F_sceSyscon_driver_0112
	IMPORT_FUNC	"sceSyscon_driver",0xD5340103,sceSysconBatteryGetSerial
#endif
#ifdef F_sceSyscon_driver_0113
	IMPORT_FUNC	"sceSyscon_driver",0xD8471760,sceSyscon_driver_D8471760
#endif
#ifdef F_sceSyscon_driver_0114
	IMPORT_FUNC	"sceSyscon_driver",0xE00BFC9E,sceSyscon_driver_E00BFC9E
#endif
#ifdef F_sceSyscon_driver_0115
	IMPORT_FUNC	"sceSyscon_driver",0xE0DDFE18,sceSysconGetHPConnect
#endif
#ifdef F_sceSyscon_driver_0116
	IMPORT_FUNC	"sceSyscon_driver",0xE20D08FE,sceSyscon_driver_E20D08FE
#endif
#ifdef F_sceSyscon_driver_0117
	IMPORT_FUNC	"sceSyscon_driver",0xE448FD3F,sceSysconBatteryNop
#endif
#ifdef F_sceSyscon_driver_0118
	IMPORT_FUNC	"sceSyscon_driver",0xE540E532,sceSyscon_driver_E540E532
#endif
#ifdef F_sceSyscon_driver_0119
	IMPORT_FUNC	"sceSyscon_driver",0xE5E35721,sceSyscon_driver_E5E35721
#endif
#ifdef F_sceSyscon_driver_0120
	IMPORT_FUNC	"sceSyscon_driver",0xE6B74CB9,sceSysconNop
#endif
#ifdef F_sceSyscon_driver_0121
	IMPORT_FUNC	"sceSyscon_driver",0xE7E87741,sceSysconGetPommelVersion
#endif
#ifdef F_sceSyscon_driver_0122
	IMPORT_FUNC	"sceSyscon_driver",0xE9FF8226,sceSysconSetUSBStatus
#endif
#ifdef F_sceSyscon_driver_0123
	IMPORT_FUNC	"sceSyscon_driver",0xEA5B9823,sceSysconIsAlarmed
#endif
#ifdef F_sceSyscon_driver_0124
	IMPORT_FUNC	"sceSyscon_driver",0xEAB13FBE,sceSyscon_driver_EAB13FBE
#endif
#ifdef F_sceSyscon_driver_0125
	IMPORT_FUNC	"sceSyscon_driver",0xEB277C88,sceSyscon_driver_EB277C88
#endif
#ifdef F_sceSyscon_driver_0126
	IMPORT_FUNC	"sceSyscon_driver",0xEC0DE439,sceSysconGetPowerSwitch
#endif
#ifdef F_sceSyscon_driver_0127
	IMPORT_FUNC	"sceSyscon_driver",0xEC37C549,sceSysconGetWlanPowerCtrl
#endif
#ifdef F_sceSyscon_driver_0128
	IMPORT_FUNC	"sceSyscon_driver",0xEE81C5B1,sceSysconGetUsbPowerCtrl
#endif
#ifdef F_sceSyscon_driver_0129
	IMPORT_FUNC	"sceSyscon_driver",0xF0ED3255,sceSysconCtrlWlanPower
#endif
#ifdef F_sceSyscon_driver_0130
	IMPORT_FUNC	"sceSyscon_driver",0xF281805D,sceSysconSetPowerSwitchCallback
#endif
#ifdef F_sceSyscon_driver_0131
	IMPORT_FUNC	"sceSyscon_driver",0xF350F666,sceSysconCmdSync
#endif
#ifdef F_sceSyscon_driver_0132
	IMPORT_FUNC	"sceSyscon_driver",0xF6BB4649,sceSysconGetHoldSwitch
#endif
#ifdef F_sceSyscon_driver_0133
	IMPORT_FUNC	"sceSyscon_driver",0xF775BC34,sceSyscon_driver_F775BC34
#endif
#ifdef F_sceSyscon_driver_0134
	IMPORT_FUNC	"sceSyscon_driver",0xF9193EC3,sceSysconSetWlanPowerCallback
#endif
#ifdef F_sceSyscon_driver_0135
	IMPORT_FUNC	"sceSyscon_driver",0xF953EF93,sceSyscon_driver_F953EF93
#endif
#ifdef F_sceSyscon_driver_0136
	IMPORT_FUNC	"sceSyscon_driver",0xF9FDAFA5,sceSyscon_driver_F9FDAFA5
#endif
#ifdef F_sceSyscon_driver_0137
	IMPORT_FUNC	"sceSyscon_driver",0xFA4C4518,sceSysconBatteryGetInfo
#endif
#ifdef F_sceSyscon_driver_0138
	IMPORT_FUNC	"sceSyscon_driver",0xFB148FB6,sceSyscon_driver_FB148FB6
#endif
#ifdef F_sceSyscon_driver_0139
	IMPORT_FUNC	"sceSyscon_driver",0xFC32141A,sceSysconGetPowerSupplyStatus
#endif
