	.set noreorder

#include "pspimport.s"

// Build List
// KDebugForKernel_0000.o KDebugForKernel_0001.o KDebugForKernel_0002.o KDebugForKernel_0003.o KDebugForKernel_0004.o KDebugForKernel_0005.o KDebugForKernel_0006.o KDebugForKernel_0007.o KDebugForKernel_0008.o KDebugForKernel_0009.o KDebugForKernel_0010.o KDebugForKernel_0011.o KDebugForKernel_0012.o KDebugForKernel_0013.o KDebugForKernel_0014.o KDebugForKernel_0015.o KDebugForKernel_0016.o KDebugForKernel_0017.o KDebugForKernel_0018.o KDebugForKernel_0019.o KDebugForKernel_0020.o KDebugForKernel_0021.o KDebugForKernel_0022.o KDebugForKernel_0023.o KDebugForKernel_0024.o KDebugForKernel_0025.o KDebugForKernel_0026.o KDebugForKernel_0027.o KDebugForKernel_0028.o KDebugForKernel_0029.o 

#ifdef F_KDebugForKernel_0000
	IMPORT_START	"KDebugForKernel",0x00010011
#endif
#ifdef F_KDebugForKernel_0001
	IMPORT_FUNC	"KDebugForKernel",0x0F3A20AC,KDebugForKernel_0F3A20AC
#endif
#ifdef F_KDebugForKernel_0002
	IMPORT_FUNC	"KDebugForKernel",0x20AA35E6,KDebugForKernel_20AA35E6
#endif
#ifdef F_KDebugForKernel_0003
	IMPORT_FUNC	"KDebugForKernel",0x30D99C9F,KDebugForKernel_30D99C9F
#endif
#ifdef F_KDebugForKernel_0004
	IMPORT_FUNC	"KDebugForKernel",0x3C87A139,KDebugForKernel_3C87A139
#endif
#ifdef F_KDebugForKernel_0005
	IMPORT_FUNC	"KDebugForKernel",0x41837A75,KDebugForKernel_41837A75
#endif
#ifdef F_KDebugForKernel_0006
	IMPORT_FUNC	"KDebugForKernel",0x4C4BCAFB,KDebugForKernel_4C4BCAFB
#endif
#ifdef F_KDebugForKernel_0007
	IMPORT_FUNC	"KDebugForKernel",0x5152709D,KDebugForKernel_5152709D
#endif
#ifdef F_KDebugForKernel_0008
	IMPORT_FUNC	"KDebugForKernel",0x623C50CD,KDebugForKernel_623C50CD
#endif
#ifdef F_KDebugForKernel_0009
	IMPORT_FUNC	"KDebugForKernel",0x6C002CDA,KDebugForKernel_6C002CDA
#endif
#ifdef F_KDebugForKernel_0010
	IMPORT_FUNC	"KDebugForKernel",0x71AD79FF,KDebugForKernel_71AD79FF
#endif
#ifdef F_KDebugForKernel_0011
	IMPORT_FUNC	"KDebugForKernel",0x730A66C0,KDebugForKernel_730A66C0
#endif
#ifdef F_KDebugForKernel_0012
	IMPORT_FUNC	"KDebugForKernel",0x7741ACF6,KDebugForKernel_7741ACF6
#endif
#ifdef F_KDebugForKernel_0013
	IMPORT_FUNC	"KDebugForKernel",0x84F370BC,Kprintf
#endif
#ifdef F_KDebugForKernel_0014
	IMPORT_FUNC	"KDebugForKernel",0x870372BD,KDebugForKernel_870372BD
#endif
#ifdef F_KDebugForKernel_0015
	IMPORT_FUNC	"KDebugForKernel",0x89E27CFC,KDebugForKernel_89E27CFC
#endif
#ifdef F_KDebugForKernel_0016
	IMPORT_FUNC	"KDebugForKernel",0x91B9B661,KDebugForKernel_91B9B661
#endif
#ifdef F_KDebugForKernel_0017
	IMPORT_FUNC	"KDebugForKernel",0x9343FC46,KDebugForKernel_9343FC46
#endif
#ifdef F_KDebugForKernel_0018
	IMPORT_FUNC	"KDebugForKernel",0x9A735384,KDebugForKernel_9A735384
#endif
#ifdef F_KDebugForKernel_0019
	IMPORT_FUNC	"KDebugForKernel",0x9AF953FF,KDebugForKernel_9AF953FF
#endif
#ifdef F_KDebugForKernel_0020
	IMPORT_FUNC	"KDebugForKernel",0xA39CBC8A,KDebugForKernel_A39CBC8A
#endif
#ifdef F_KDebugForKernel_0021
	IMPORT_FUNC	"KDebugForKernel",0xB6536B46,KDebugForKernel_B6536B46
#endif
#ifdef F_KDebugForKernel_0022
	IMPORT_FUNC	"KDebugForKernel",0xCD8423A2,KDebugForKernel_CD8423A2
#endif
#ifdef F_KDebugForKernel_0023
	IMPORT_FUNC	"KDebugForKernel",0xD636B827,sceKernelRemoveByDebugSection
#endif
#ifdef F_KDebugForKernel_0024
	IMPORT_FUNC	"KDebugForKernel",0xE892D9A1,KDebugForKernel_E892D9A1
#endif
#ifdef F_KDebugForKernel_0025
	IMPORT_FUNC	"KDebugForKernel",0xEF30654A,KDebugForKernel_EF30654A
#endif
#ifdef F_KDebugForKernel_0026
	IMPORT_FUNC	"KDebugForKernel",0xF6FCA1F5,KDebugForKernel_F6FCA1F5
#endif
#ifdef F_KDebugForKernel_0027
	IMPORT_FUNC	"KDebugForKernel",0xFDFE9698,KDebugForKernel_FDFE9698
#endif
#ifdef F_KDebugForKernel_0028
	IMPORT_FUNC	"KDebugForKernel",0xFE3062B8,KDebugForKernel_FE3062B8
#endif
#ifdef F_KDebugForKernel_0029
	IMPORT_FUNC	"KDebugForKernel",0xFF21DA23,KDebugForKernel_FF21DA23
#endif
