release: all
	   psppacker 380I march33.prx

TARGET = march33
OBJS = main.o umd9660.o isoread.o csoread.o umdman.o mediaman.o exports.o

INCDIR = ../include
CFLAGS = -O2 -G0 -Wall -fshort-wchar -fno-pic -mno-check-zero-division 
CXXFLAGS = $(CFLAGS) -fno-exceptions -fno-rtti
ASFLAGS = $(CFLAGS)

BUILD_PRX = 1
PRX_EXPORTS = exports.exp

USE_KERNEL_LIBC = 1
USE_KERNEL_LIBS = 1

PSP_FW_VERSION = 380

LIBDIR = ../lib
LIBS = -lpspsysmem_kernel  -lpspsystemctrl_kernel
LDFLAGS =  -nostdlib -nodefaultlibs

PSPSDK=$(shell psp-config --pspsdk-path)
include $(PSPSDK)/lib/build_prx.mak

