	.set noreorder

#include "pspimport.s"



#ifdef F_sceVshBridge_0000
	IMPORT_START	"sceVshBridge",0x40010011
#endif
#ifdef F_sceVshBridge_0001
	IMPORT_FUNC	"sceVshBridge",0x002381F2,sceVshBridge_002381F2
#endif
#ifdef F_sceVshBridge_0002
	IMPORT_FUNC	"sceVshBridge",0x00CD4949,vshKernelLoadExecVSHMs4
#endif
#ifdef F_sceVshBridge_0003
	IMPORT_FUNC	"sceVshBridge",0x0556CCAE,sceVshBridge_0556CCAE
#endif
#ifdef F_sceVshBridge_0004
	IMPORT_FUNC	"sceVshBridge",0x08858CBF,vshKernelLoadExecBufferVSHUsbWlan
#endif
#ifdef F_sceVshBridge_0005
	IMPORT_FUNC	"sceVshBridge",0x0E87EC0C,sceVshBridge_0E87EC0C
#endif
#ifdef F_sceVshBridge_0006
	IMPORT_FUNC	"sceVshBridge",0x12701700,sceVshBridge_12701700
#endif
#ifdef F_sceVshBridge_0007
	IMPORT_FUNC	"sceVshBridge",0x1A5FD1E6,sceVshBridge_1A5FD1E6
#endif
#ifdef F_sceVshBridge_0008
	IMPORT_FUNC	"sceVshBridge",0x1C4C47E5,sceVshBridge_1C4C47E5
#endif
#ifdef F_sceVshBridge_0009
	IMPORT_FUNC	"sceVshBridge",0x21FEB14D,sceVshBridge_21FEB14D
#endif
#ifdef F_sceVshBridge_0010
	IMPORT_FUNC	"sceVshBridge",0x2380DC08,vshIoDevctl
#endif
#ifdef F_sceVshBridge_0011
	IMPORT_FUNC	"sceVshBridge",0x2403928E,vshKernelLoadExecVSHDiscDebug
#endif
#ifdef F_sceVshBridge_0012
	IMPORT_FUNC	"sceVshBridge",0x243B7C57,sceVshBridge_243B7C57
#endif
#ifdef F_sceVshBridge_0013
	IMPORT_FUNC	"sceVshBridge",0x24B92584,sceVshBridge_24B92584
#endif
#ifdef F_sceVshBridge_0014
	IMPORT_FUNC	"sceVshBridge",0x24C921AC,sceVshBridge_24C921AC
#endif
#ifdef F_sceVshBridge_0015
	IMPORT_FUNC	"sceVshBridge",0x2686B113,sceVshBridge_2686B113
#endif
#ifdef F_sceVshBridge_0016
	IMPORT_FUNC	"sceVshBridge",0x27998D2C,sceVshBridge_27998D2C
#endif
#ifdef F_sceVshBridge_0017
	IMPORT_FUNC	"sceVshBridge",0x2E273B01,sceVshBridge_2E273B01
#endif
#ifdef F_sceVshBridge_0018
	IMPORT_FUNC	"sceVshBridge",0x2F602CB1,sceVshBridge_2F602CB1
#endif
#ifdef F_sceVshBridge_0019
	IMPORT_FUNC	"sceVshBridge",0x3007DFB3,sceVshBridge_3007DFB3
#endif
#ifdef F_sceVshBridge_0020
	IMPORT_FUNC	"sceVshBridge",0x31B2D587,sceVshBridge_31B2D587
#endif
#ifdef F_sceVshBridge_0021
	IMPORT_FUNC	"sceVshBridge",0x336ACD3B,sceVshBridge_336ACD3B
#endif
#ifdef F_sceVshBridge_0022
	IMPORT_FUNC	"sceVshBridge",0x35C28163,sceVshBridge_35C28163
#endif
#ifdef F_sceVshBridge_0023
	IMPORT_FUNC	"sceVshBridge",0x38B9DCB1,sceVshBridge_38B9DCB1
#endif
#ifdef F_sceVshBridge_0024
	IMPORT_FUNC	"sceVshBridge",0x38D115DD,sceVshBridge_38D115DD
#endif
#ifdef F_sceVshBridge_0025
	IMPORT_FUNC	"sceVshBridge",0x39B499E0,sceVshBridge_39B499E0
#endif
#ifdef F_sceVshBridge_0026
	IMPORT_FUNC	"sceVshBridge",0x3E176AD8,sceVshBridge_3E176AD8
#endif
#ifdef F_sceVshBridge_0027
	IMPORT_FUNC	"sceVshBridge",0x3EE685DE,sceVshBridge_3EE685DE
#endif
#ifdef F_sceVshBridge_0028
	IMPORT_FUNC	"sceVshBridge",0x3FCFF39E,sceVshBridge_3FCFF39E
#endif
#ifdef F_sceVshBridge_0029
	IMPORT_FUNC	"sceVshBridge",0x40DC2749,sceVshBridge_40DC2749
#endif
#ifdef F_sceVshBridge_0030
	IMPORT_FUNC	"sceVshBridge",0x41C54ADF,vshKernelLoadModuleVSHByID
#endif
#ifdef F_sceVshBridge_0031
	IMPORT_FUNC	"sceVshBridge",0x427D6063,sceVshBridge_427D6063
#endif
#ifdef F_sceVshBridge_0032
	IMPORT_FUNC	"sceVshBridge",0x0F866DE2,vshKernelLoadExecVSHMs2
#endif
#ifdef F_sceVshBridge_0033
	IMPORT_FUNC	"sceVshBridge",0x458D27BF,vshKernelLoadExecVSHDiscUpdater
#endif
#ifdef F_sceVshBridge_0034
	IMPORT_FUNC	"sceVshBridge",0x46586131,sceVshBridge_46586131
#endif
#ifdef F_sceVshBridge_0035
	IMPORT_FUNC	"sceVshBridge",0x4853573E,sceVshBridge_4853573E
#endif
#ifdef F_sceVshBridge_0036
	IMPORT_FUNC	"sceVshBridge",0x4A596D2D,vshImposeSetParam
#endif
#ifdef F_sceVshBridge_0037
	IMPORT_FUNC	"sceVshBridge",0x4CA1F6DA,sceVshBridge_4CA1F6DA
#endif
#ifdef F_sceVshBridge_0038
	IMPORT_FUNC	"sceVshBridge",0x4DB43867,vshIdStorageLookup
#endif
#ifdef F_sceVshBridge_0039
	IMPORT_FUNC	"sceVshBridge",0x4DFE1669,sceVshBridge_4DFE1669
#endif
#ifdef F_sceVshBridge_0040
	IMPORT_FUNC	"sceVshBridge",0x4E4E4DA3,vshImposeSetStatus
#endif
#ifdef F_sceVshBridge_0041
	IMPORT_FUNC	"sceVshBridge",0x4EC06FA4,sceVshBridge_4EC06FA4
#endif
#ifdef F_sceVshBridge_0042
	IMPORT_FUNC	"sceVshBridge",0x51CC70F5,sceVshBridge_51CC70F5
#endif
#ifdef F_sceVshBridge_0043
	IMPORT_FUNC	"sceVshBridge",0x5203C2A2,sceVshBridge_5203C2A2
#endif
#ifdef F_sceVshBridge_0044
	IMPORT_FUNC	"sceVshBridge",0x520CB18D,sceVshBridge_520CB18D
#endif
#ifdef F_sceVshBridge_0045
	IMPORT_FUNC	"sceVshBridge",0x5317A582,sceVshBridge_5317A582
#endif
#ifdef F_sceVshBridge_0046
	IMPORT_FUNC	"sceVshBridge",0x53BFD101,vshMSAudioCheckICV
#endif
#ifdef F_sceVshBridge_0047
	IMPORT_FUNC	"sceVshBridge",0x5434B104,sceVshBridge_5434B104
#endif
#ifdef F_sceVshBridge_0048
	IMPORT_FUNC	"sceVshBridge",0x543DF545,sceVshBridge_543DF545
#endif
#ifdef F_sceVshBridge_0049
	IMPORT_FUNC	"sceVshBridge",0x57F60A8E,sceVshBridge_57F60A8E
#endif
#ifdef F_sceVshBridge_0050
	IMPORT_FUNC	"sceVshBridge",0x5894C339,vshImposeChanges
#endif
#ifdef F_sceVshBridge_0051
	IMPORT_FUNC	"sceVshBridge",0x59343B13,sceVshBridge_59343B13
#endif
#ifdef F_sceVshBridge_0052
	IMPORT_FUNC	"sceVshBridge",0x5C2983C2,vshChkregCheckRegion
#endif
#ifdef F_sceVshBridge_0053
	IMPORT_FUNC	"sceVshBridge",0x5D76A0D7,sceVshBridge_5D76A0D7
#endif
#ifdef F_sceVshBridge_0054
	IMPORT_FUNC	"sceVshBridge",0x5DA71899,sceVshBridge_5DA71899
#endif
#ifdef F_sceVshBridge_0055
	IMPORT_FUNC	"sceVshBridge",0x60C6E226,sceVshBridge_60C6E226
#endif
#ifdef F_sceVshBridge_0056
	IMPORT_FUNC	"sceVshBridge",0x61001D64,vshChkregGetPsCode
#endif
#ifdef F_sceVshBridge_0057
	IMPORT_FUNC	"sceVshBridge",0x639C3CB3,vshImposeGetParam
#endif
#ifdef F_sceVshBridge_0058
	IMPORT_FUNC	"sceVshBridge",0x65742115,sceVshBridge_65742115
#endif
#ifdef F_sceVshBridge_0059
	IMPORT_FUNC	"sceVshBridge",0x689DC2B0,sceVshBridge_689DC2B0
#endif
#ifdef F_sceVshBridge_0060
	IMPORT_FUNC	"sceVshBridge",0x69A60766,sceVshBridge_69A60766
#endif
#ifdef F_sceVshBridge_0061
	IMPORT_FUNC	"sceVshBridge",0x6BED8184,sceVshBridge_6BED8184
#endif
#ifdef F_sceVshBridge_0062
	IMPORT_FUNC	"sceVshBridge",0x6CAEB765,vshMSAudioAuth
#endif
#ifdef F_sceVshBridge_0063
	IMPORT_FUNC	"sceVshBridge",0x6DDF0045,sceVshBridge_6DDF0045
#endif
#ifdef F_sceVshBridge_0064
	IMPORT_FUNC	"sceVshBridge",0x74DA9D25,vshLflashFatfmtStartFatfmt
#endif
#ifdef F_sceVshBridge_0065
	IMPORT_FUNC	"sceVshBridge",0x74DB2D30,vshKernelLoadExecVSHDisc
#endif
#ifdef F_sceVshBridge_0066
	IMPORT_FUNC	"sceVshBridge",0x75591C45,sceVshBridge_75591C45
#endif
#ifdef F_sceVshBridge_0067
	IMPORT_FUNC	"sceVshBridge",0x76120766,vshKernelExitVSHVSH
#endif
#ifdef F_sceVshBridge_0068
	IMPORT_FUNC	"sceVshBridge",0x75A512CC,vshKernelLoadExecBufferVSHUsbWlanDebug
#endif
#ifdef F_sceVshBridge_0069
	IMPORT_FUNC	"sceVshBridge",0x75EFA3D4,sceVshBridge_75EFA3D4
#endif
#ifdef F_sceVshBridge_0070
	IMPORT_FUNC	"sceVshBridge",0x761A11F1,sceVshBridge_761A11F1
#endif
#ifdef F_sceVshBridge_0071
	IMPORT_FUNC	"sceVshBridge",0x78A4D7E4,sceVshBridge_78A4D7E4
#endif
#ifdef F_sceVshBridge_0072
	IMPORT_FUNC	"sceVshBridge",0x7B85B850,sceVshBridge_7B85B850
#endif
#ifdef F_sceVshBridge_0073
	IMPORT_FUNC	"sceVshBridge",0x7BB63511,sceVshBridge_7BB63511
#endif
#ifdef F_sceVshBridge_0074
	IMPORT_FUNC	"sceVshBridge",0x7E092ADF,sceVshBridge_7E092ADF
#endif
#ifdef F_sceVshBridge_0075
	IMPORT_FUNC	"sceVshBridge",0x7EA32357,vshMSAudioDeauth
#endif
#ifdef F_sceVshBridge_0076
	IMPORT_FUNC	"sceVshBridge",0x815782DB,sceVshBridge_815782DB
#endif
#ifdef F_sceVshBridge_0077
	IMPORT_FUNC	"sceVshBridge",0x81FD3FF4,sceVshBridge_81FD3FF4
#endif
#ifdef F_sceVshBridge_0078
	IMPORT_FUNC	"sceVshBridge",0x82314DEE,sceVshBridge_82314DEE
#endif
#ifdef F_sceVshBridge_0079
	IMPORT_FUNC	"sceVshBridge",0x834FF53D,sceVshBridge_834FF53D
#endif
#ifdef F_sceVshBridge_0080
	IMPORT_FUNC	"sceVshBridge",0x8EF3A0DA,sceVshBridge_8EF3A0DA
#endif
#ifdef F_sceVshBridge_0081
	IMPORT_FUNC	"sceVshBridge",0x925EE68C,sceVshBridge_925EE68C
#endif
#ifdef F_sceVshBridge_0082
	IMPORT_FUNC	"sceVshBridge",0x95C9D89F,sceVshBridge_95C9D89F
#endif
#ifdef F_sceVshBridge_0083
	IMPORT_FUNC	"sceVshBridge",0x96E6098F,sceVshBridge_96E6098F
#endif
#ifdef F_sceVshBridge_0084
	IMPORT_FUNC	"sceVshBridge",0x9BA6BE17,sceVshBridge_9BA6BE17
#endif
#ifdef F_sceVshBridge_0085
	IMPORT_FUNC	"sceVshBridge",0x9BBA642D,sceVshBridge_9BBA642D
#endif
#ifdef F_sceVshBridge_0086
	IMPORT_FUNC	"sceVshBridge",0xA0A10648,sceVshBridge_A0A10648
#endif
#ifdef F_sceVshBridge_0087
	IMPORT_FUNC	"sceVshBridge",0xA5628F0D,vshKernelLoadModuleVSH
#endif
#ifdef F_sceVshBridge_0088
	IMPORT_FUNC	"sceVshBridge",0xA7724D4A,sceVshBridge_A7724D4A
#endif
#ifdef F_sceVshBridge_0089
	IMPORT_FUNC	"sceVshBridge",0xA77FD0D9,sceVshBridge_A77FD0D9
#endif
#ifdef F_sceVshBridge_0090
	IMPORT_FUNC	"sceVshBridge",0xA9574AF7,sceVshBridge_A9574AF7
#endif
#ifdef F_sceVshBridge_0091
	IMPORT_FUNC	"sceVshBridge",0xABDF01CC,sceVshBridge_ABDF01CC
#endif
#ifdef F_sceVshBridge_0092
	IMPORT_FUNC	"sceVshBridge",0xB14D3E2D,sceVshBridge_B14D3E2D
#endif
#ifdef F_sceVshBridge_0093
	IMPORT_FUNC	"sceVshBridge",0xB1A1A24C,vshKernelLoadExecVSHMs3
#endif
#ifdef F_sceVshBridge_0094
	IMPORT_FUNC	"sceVshBridge",0xB4235201,sceVshBridge_B4235201
#endif
#ifdef F_sceVshBridge_0095
	IMPORT_FUNC	"sceVshBridge",0xB472AC68,sceVshBridge_B472AC68
#endif
#ifdef F_sceVshBridge_0096
	IMPORT_FUNC	"sceVshBridge",0xB62A78F4,vshKernelLoadExecVSHMs5
#endif
#ifdef F_sceVshBridge_0097
	IMPORT_FUNC	"sceVshBridge",0xB6E618B8,sceVshBridge_B6E618B8
#endif
#ifdef F_sceVshBridge_0098
	IMPORT_FUNC	"sceVshBridge",0xB840EDB2,sceVshBridge_B840EDB2
#endif
#ifdef F_sceVshBridge_0099
	IMPORT_FUNC	"sceVshBridge",0xB98D260C,sceVshBridge_B98D260C
#endif
#ifdef F_sceVshBridge_0100
	IMPORT_FUNC	"sceVshBridge",0xBC8A6ACB,sceVshBridge_BC8A6ACB
#endif
#ifdef F_sceVshBridge_0101
	IMPORT_FUNC	"sceVshBridge",0xBE38F663,sceVshBridge_BE38F663
#endif
#ifdef F_sceVshBridge_0102
	IMPORT_FUNC	"sceVshBridge",0xBF107306,sceVshBridge_BF107306
#endif
#ifdef F_sceVshBridge_0103
	IMPORT_FUNC	"sceVshBridge",0xBF25C8F3,sceVshBridge_BF25C8F3
#endif
#ifdef F_sceVshBridge_0104
	IMPORT_FUNC	"sceVshBridge",0xC11F2846,sceVshBridge_C11F2846
#endif
#ifdef F_sceVshBridge_0105
	IMPORT_FUNC	"sceVshBridge",0xC27161C0,sceVshBridge_C27161C0
#endif
#ifdef F_sceVshBridge_0106
	IMPORT_FUNC	"sceVshBridge",0xC62E0B0D,sceVshBridge_C62E0B0D
#endif
#ifdef F_sceVshBridge_0107
	IMPORT_FUNC	"sceVshBridge",0xC6395C03,vshCtrlReadBufferPositive
#endif
#ifdef F_sceVshBridge_0108
	IMPORT_FUNC	"sceVshBridge",0xC775F34A,sceVshBridge_C775F34A
#endif
#ifdef F_sceVshBridge_0109
	IMPORT_FUNC	"sceVshBridge",0xC86E65DC,sceVshBridge_C86E65DC
#endif
#ifdef F_sceVshBridge_0110
	IMPORT_FUNC	"sceVshBridge",0xC949966C,sceVshBridge_C949966C
#endif
#ifdef F_sceVshBridge_0111
	IMPORT_FUNC	"sceVshBridge",0xC9626587,vshKernelLoadModuleBufferVSH
#endif
#ifdef F_sceVshBridge_0112
	IMPORT_FUNC	"sceVshBridge",0xCA719C34,vshImposeGetStatus
#endif
#ifdef F_sceVshBridge_0113
	IMPORT_FUNC	"sceVshBridge",0xCB003780,sceVshBridge_CB003780
#endif
#ifdef F_sceVshBridge_0114
	IMPORT_FUNC	"sceVshBridge",0xCC2994C8,sceVshBridge_CC2994C8
#endif
#ifdef F_sceVshBridge_0115
	IMPORT_FUNC	"sceVshBridge",0xCCF369F3,vshKernelLoadExecVSHMs1
#endif
#ifdef F_sceVshBridge_0116
	IMPORT_FUNC	"sceVshBridge",0xA2788872,vshKernelGetModel
#endif
#ifdef F_sceVshBridge_0117
	IMPORT_FUNC	"sceVshBridge",0xCE32CBEF,vshMSAudioInit
#endif
#ifdef F_sceVshBridge_0118
	IMPORT_FUNC	"sceVshBridge",0xCE4BA2EB,sceVshBridge_CE4BA2EB
#endif
#ifdef F_sceVshBridge_0119
	IMPORT_FUNC	"sceVshBridge",0xD01DF045,sceVshBridge_D01DF045
#endif
#ifdef F_sceVshBridge_0120
	IMPORT_FUNC	"sceVshBridge",0xD3C933A0,sceVshBridge_D3C933A0
#endif
#ifdef F_sceVshBridge_0121
	IMPORT_FUNC	"sceVshBridge",0xD717671A,sceVshBridge_D717671A
#endif
#ifdef F_sceVshBridge_0122
	IMPORT_FUNC	"sceVshBridge",0xD8CE03B8,sceVshBridge_D8CE03B8
#endif
#ifdef F_sceVshBridge_0123
	IMPORT_FUNC	"sceVshBridge",0xD91D5BB9,sceVshBridge_D91D5BB9
#endif
#ifdef F_sceVshBridge_0124
	IMPORT_FUNC	"sceVshBridge",0xDAE3A119,sceVshBridge_DAE3A119
#endif
#ifdef F_sceVshBridge_0125
	IMPORT_FUNC	"sceVshBridge",0xDFB85AB2,sceVshBridge_DFB85AB2
#endif
#ifdef F_sceVshBridge_0126
	IMPORT_FUNC	"sceVshBridge",0xE174218C,vshInputEndSetEventEnable
#endif
#ifdef F_sceVshBridge_0127
	IMPORT_FUNC	"sceVshBridge",0xE192FCAA,sceVshBridge_E192FCAA
#endif
#ifdef F_sceVshBridge_0128
	IMPORT_FUNC	"sceVshBridge",0xE1941520,sceVshBridge_E1941520
#endif
#ifdef F_sceVshBridge_0129
	IMPORT_FUNC	"sceVshBridge",0xE5DA5E95,vshMSAudioEnd
#endif
#ifdef F_sceVshBridge_0130
	IMPORT_FUNC	"sceVshBridge",0xF1267A95,sceVshBridge_F1267A95
#endif
#ifdef F_sceVshBridge_0131
	IMPORT_FUNC	"sceVshBridge",0xF35CE1C8,sceVshBridge_F35CE1C8
#endif
#ifdef F_sceVshBridge_0132
	IMPORT_FUNC	"sceVshBridge",0xF4BD7905,sceVshBridge_F4BD7905
#endif
#ifdef F_sceVshBridge_0133
	IMPORT_FUNC	"sceVshBridge",0xFC0975E8,sceVshBridge_FC0975E8
#endif
#ifdef F_sceVshBridge_0134
	IMPORT_FUNC	"sceVshBridge",0xFD304180,sceVshBridge_FD304180
#endif
#ifdef F_sceVshBridge_0135
	IMPORT_FUNC	"sceVshBridge",0xFDDE5CA3,sceVshBridge_FDDE5CA3
#endif
