	.set noreorder

#include "pspimport.s"

// Build List
// LoadExecForKernel_0000.o LoadExecForKernel_0001.o LoadExecForKernel_0002.o LoadExecForKernel_0003.o LoadExecForKernel_0004.o LoadExecForKernel_0005.o LoadExecForKernel_0006.o LoadExecForKernel_0007.o LoadExecForKernel_0008.o LoadExecForKernel_0009.o LoadExecForKernel_0010.o LoadExecForKernel_0011.o LoadExecForKernel_0012.o LoadExecForKernel_0013.o LoadExecForKernel_0014.o LoadExecForKernel_0015.o LoadExecForKernel_0016.o LoadExecForKernel_0017.o LoadExecForKernel_0018.o 

#ifdef F_LoadExecForKernel_0000
	IMPORT_START	"LoadExecForKernel",0x00090011
#endif
#ifdef F_LoadExecForKernel_0001
	IMPORT_FUNC	"LoadExecForKernel",0x015DA036,sceKernelLoadExecBufferVSHUsbWlan
#endif
#ifdef F_LoadExecForKernel_0002
	IMPORT_FUNC	"LoadExecForKernel",0x061D9514,sceKernelLoadExecVSHMs4
#endif
#ifdef F_LoadExecForKernel_0003
	IMPORT_FUNC	"LoadExecForKernel",0x11412288,LoadExecForKernel_11412288
#endif
#ifdef F_LoadExecForKernel_0004
	IMPORT_FUNC	"LoadExecForKernel",0x1B97BDB3,sceKernelLoadExecVSHDisc
#endif
#ifdef F_LoadExecForKernel_0005
	IMPORT_FUNC	"LoadExecForKernel",0x28D0D249,sceKernelLoadExecVSHMs2
#endif
#ifdef F_LoadExecForKernel_0006
	IMPORT_FUNC	"LoadExecForKernel",0x31DF42BF,sceKernelLoadExecVSHMs1
#endif
#ifdef F_LoadExecForKernel_0007
	IMPORT_FUNC	"LoadExecForKernel",0x4AC57943,sceKernelRegisterExitCallback
#endif
#ifdef F_LoadExecForKernel_0008
	IMPORT_FUNC	"LoadExecForKernel",0x4F41E75E,sceKernelLoadExecBufferVSHUsbWlanDebug
#endif
#ifdef F_LoadExecForKernel_0009
	IMPORT_FUNC	"LoadExecForKernel",0x62A27008,sceKernelInvokeExitCallback
#endif
#ifdef F_LoadExecForKernel_0010
	IMPORT_FUNC	"LoadExecForKernel",0x659188E1,sceKernelCheckExitCallback
#endif
#ifdef F_LoadExecForKernel_0011
	IMPORT_FUNC	"LoadExecForKernel",0x6D302D3D,sceKernelExitVSHKernel
#endif
#ifdef F_LoadExecForKernel_0012
	IMPORT_FUNC	"LoadExecForKernel",0x6D8D3A3A,LoadExecForKernel_6D8D3A3A
#endif
#ifdef F_LoadExecForKernel_0013
	IMPORT_FUNC	"LoadExecForKernel",0x70901231,sceKernelLoadExecVSHMs3
#endif
#ifdef F_LoadExecForKernel_0014
	IMPORT_FUNC	"LoadExecForKernel",0x7B7C47EF,sceKernelLoadExecVSHDiscDebug
#endif
#ifdef F_LoadExecForKernel_0015
	IMPORT_FUNC	"LoadExecForKernel",0x821BE114,sceKernelLoadExecVSHDiscUpdater
#endif
#ifdef F_LoadExecForKernel_0016
	IMPORT_FUNC	"LoadExecForKernel",0xA3D5E142,sceKernelExitVSHVSH
#endif
#ifdef F_LoadExecForKernel_0017
	IMPORT_FUNC	"LoadExecForKernel",0xB7AB08DA,sceKernelLoadExecVSHMs5
#endif
#ifdef F_LoadExecForKernel_0018
	IMPORT_FUNC	"LoadExecForKernel",0xD9739B89,sceKernelUnregisterExitCallback
#endif
