	.set noreorder

#include "pspimport.s"

// Build List
// scePspNpDrm_driver_0000.o scePspNpDrm_driver_0001.o scePspNpDrm_driver_0002.o scePspNpDrm_driver_0003.o scePspNpDrm_driver_0004.o scePspNpDrm_driver_0005.o scePspNpDrm_driver_0006.o 

#ifdef F_scePspNpDrm_driver_0000
	IMPORT_START	"scePspNpDrm_driver",0x00010011
#endif
#ifdef F_scePspNpDrm_driver_0001
	IMPORT_FUNC	"scePspNpDrm_driver",0x04618D16,scePspNpDrm_driver_04618D16
#endif
#ifdef F_scePspNpDrm_driver_0002
	IMPORT_FUNC	"scePspNpDrm_driver",0x0F9547E6,scePspNpDrm_driver_0F9547E6
#endif
#ifdef F_scePspNpDrm_driver_0003
	IMPORT_FUNC	"scePspNpDrm_driver",0x17E3F4BB,scePspNpDrm_driver_17E3F4BB
#endif
#ifdef F_scePspNpDrm_driver_0004
	IMPORT_FUNC	"scePspNpDrm_driver",0x37B9B10D,scePspNpDrm_driver_37B9B10D
#endif
#ifdef F_scePspNpDrm_driver_0005
	IMPORT_FUNC	"scePspNpDrm_driver",0x5667B7B9,scePspNpDrm_driver_5667B7B9
#endif
#ifdef F_scePspNpDrm_driver_0006
	IMPORT_FUNC	"scePspNpDrm_driver",0xEBB198ED,scePspNpDrm_driver_EBB198ED
#endif
