	.set noreorder

#include "pspimport.s"

// Build List
// LoadExecForKernel_0000.o LoadExecForKernel_0001.o LoadExecForKernel_0002.o LoadExecForKernel_0003.o LoadExecForKernel_0004.o LoadExecForKernel_0005.o LoadExecForKernel_0006.o LoadExecForKernel_0007.o LoadExecForKernel_0008.o LoadExecForKernel_0009.o LoadExecForKernel_0010.o LoadExecForKernel_0011.o LoadExecForKernel_0012.o LoadExecForKernel_0013.o LoadExecForKernel_0014.o LoadExecForKernel_0015.o LoadExecForKernel_0016.o LoadExecForKernel_0017.o LoadExecForKernel_0018.o LoadExecForKernel_0019.o LoadExecForKernel_0020.o 

#ifdef F_LoadExecForKernel_0000
	IMPORT_START	"LoadExecForKernel",0x00090011
#endif
#ifdef F_LoadExecForKernel_0001
	IMPORT_FUNC	"LoadExecForKernel",0x0B4BF2C1,LoadExecForKernel_6D8D3A3A
#endif
#ifdef F_LoadExecForKernel_0002
	IMPORT_FUNC	"LoadExecForKernel",0x14DCA661,LoadExecForKernel_11412288
#endif
#ifdef F_LoadExecForKernel_0003
	IMPORT_FUNC	"LoadExecForKernel",0x234B2B47,sceKernelLoadExecVSHDisc
#endif
#ifdef F_LoadExecForKernel_0004
	IMPORT_FUNC	"LoadExecForKernel",0x58699192,sceKernelLoadExecVSHMs5
#endif
#ifdef F_LoadExecForKernel_0005
	IMPORT_FUNC	"LoadExecForKernel",0x62879AD8,sceKernelExitVSHVSH
#endif
#ifdef F_LoadExecForKernel_0006
	IMPORT_FUNC	"LoadExecForKernel",0x63E0A104,sceKernelLoadExecVSHMs3
#endif
#ifdef F_LoadExecForKernel_0007
	IMPORT_FUNC	"LoadExecForKernel",0x699110EB,sceKernelLoadExecBufferVSHUsbWlanDebug
#endif
#ifdef F_LoadExecForKernel_0008
	IMPORT_FUNC	"LoadExecForKernel",0x753EF37C,sceKernelCheckExitCallback
#endif
#ifdef F_LoadExecForKernel_0009
	IMPORT_FUNC	"LoadExecForKernel",0x767F2DFC,LoadExecForKernel_15EB8575
#endif
#ifdef F_LoadExecForKernel_0010
	IMPORT_FUNC	"LoadExecForKernel",0x860783BF,sceKernelInvokeExitCallback
#endif
#ifdef F_LoadExecForKernel_0011
	IMPORT_FUNC	"LoadExecForKernel",0x8D157BC7,sceKernelLoadExecVSHMs2
#endif
#ifdef F_LoadExecForKernel_0012
	IMPORT_FUNC	"LoadExecForKernel",0xAE5AC5D3,sceKernelExitVSHKernel
#endif
#ifdef F_LoadExecForKernel_0013
	IMPORT_FUNC	"LoadExecForKernel",0xAF9AB97F,sceKernelLoadExecVSHDiscUpdater
#endif
#ifdef F_LoadExecForKernel_0014
	IMPORT_FUNC	"LoadExecForKernel",0xB1B9C320,LoadExecForKernel_D3D13800
#endif
#ifdef F_LoadExecForKernel_0015
	IMPORT_FUNC	"LoadExecForKernel",0xB2F14B53,sceKernelLoadExecVSHMs1
#endif
#ifdef F_LoadExecForKernel_0016
	IMPORT_FUNC	"LoadExecForKernel",0xDB7DF065,sceKernelRegisterExitCallback
#endif
#ifdef F_LoadExecForKernel_0017
	IMPORT_FUNC	"LoadExecForKernel",0xE70C0711,sceKernelLoadExecBufferVSHUsbWlan
#endif
#ifdef F_LoadExecForKernel_0018
	IMPORT_FUNC	"LoadExecForKernel",0xF1C99C38,sceKernelUnregisterExitCallback
#endif
#ifdef F_LoadExecForKernel_0019
	IMPORT_FUNC	"LoadExecForKernel",0xF33FF989,sceKernelLoadExecVSHDiscDebug
#endif
#ifdef F_LoadExecForKernel_0020
	IMPORT_FUNC	"LoadExecForKernel",0xFC8050B0,sceKernelLoadExecVSHMs4
#endif
